version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:0.118.3
    volumes:
      - ./homeassistant:/config
      - ./certbot:/etc/letsencrypt
    environment:
      - TZ=Europe/Stockholm
    restart: always
    depends_on:
      - deconz
#    ports:
#      - "8123:8123"
    network_mode: host
  deconz:
    container_name: deconz
    image: marthoc/deconz:armhf-2.05.82
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - TZ=Europe/Stockholm
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=/dev/ttyACM0
    restart: always
    network_mode: host
#    ports:
#      - "8080:80"
  duckdns:
    container_name: duckdns
    image: pandidan/duckdns
    environment:
      - TOKEN=<TOKEN>
      - DOMAIN=<DOMAIN>
    restart: always
  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot:/etc/letsencrypt
    restart: always
    ports:
      - "58123:58123"
    depends_on:
      - homeassistant
  certbot:
    container_name: certbot
    image: pandidan/certbot
    volumes:
      - ./certbot:/etc/letsencrypt
    environment:
     - DUCKDNS_TOKEN=<DUCKDNS_TOKEN>
    # command: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: certbot certonly -n -q --agree-tos --email <EMAIL> --manual --manual-public-ip-logging-ok -d hejmo.duckdns.org --preferred-challenges dns --manual-auth-hook /etc/letsencrypt/duckdns.sh --manual-cleanup-hook "/etc/letsencrypt/duckdns.sh cleanup"
    
#  pihole:
#    container_name: pihole
#    image: pihole/pihole:latest
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "67:67/udp"
#      - "81:80/tcp"
#      - "4431:443/tcp"
#    environment:
#      TZ: 'Europe/Stockholm'
#      WEBPASSWORD: 'pihole'
#    volumes:
#       - './pihole/etc-pihole/:/etc/pihole/'
#       - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
#    dns:
#      - 127.0.0.1
#      - 1.1.1.1
#    cap_add:
#      - NET_ADMIN
#    restart: unless-stopped
